### ISSUE TITLE
Mobile Compatibility

### ISSUE THREAD

**Issue by VictorPubh** [icheer/web-assistant#1]
I worked on the implementation of Web-Assistant with Svelte for a mobile application.

During the development everything went well, the implementation was successful and the tests were carried out in Brave (it is a version of Chrome), but when validating through Safari and Chrome (now via mobile), I had problems.

Guideline: No longer displays the black screen behind the instruction after the second step.

I thought about creating several "first steps" as a way to solve it, but I'll probably just leave some instructions off.

Would you have any idea how to solve it?

**Comment by icheer** [comment]
Hi.
I have installed Kiwi Browser(based on chrome) on my mobile, and I can go through the instruction perfectly(not found the layer missing bug). Could you plz try the [live demo](https://guidebook.vercel.app/) in your Safari or Chrome browser?
Or could you send me more detail about your instruction JSON?

**Comment by VictorPubh** [comment]
See:
https://user-images.githubusercontent.com/5835796/185637395-5c3ddb1f-e189-4a9b-ad61-ca550be1994a.MOV

I did the implementation using most directives 1 step long.

The “into” has  100% worked.

**Comment by VictorPubh** [comment]
> Hi.
> I have installed Kiwi Browser(based on chrome) on my mobile, and I can go through the instruction perfectly(not found the layer missing bug). Could you plz try the [live demo](https://guidebook.vercel.app/) in your Safari or Chrome browser?
> Or could you send me more detail about your instruction JSON?

Btw, thx for your answer

**Comment by icheer** [comment]
Yes, I can reproduce the bug in Safari. I will manage to fix it soon. Thank you for the bug report.

**Comment by icheer** [comment]
Fixed it by the version 1.2.3
(Just using `await sleep(20)` instead of `await sleep(0)`, maybe it could have some better solutions, but it works now : )

**Comment by VictorPubh** [comment]
I have a new bug to report.

I tried using it with Svelte Native and the iOS native Notch and Actions Bar break the layout overlay, basically the gray part runs away from the correct place, giving the wrong focus.

I'll open a new bug later, but as for this one, that's great, I'm glad you fixed it.

Thanks for that, I'll update as soon as it's available.

**Comment by icheer** [comment]
OK, feeling glad that someone is using the web-component. I will try to fix the bug and make it easy to use.

**Comment by VictorPubh** [comment]
I thought it was amazing, if you're interested I can contribute.

Currently it is done through methods, I found it very interesting because it can be used in all cases.

But I think it could contain a component to be used through tags, even as a Web-Component used in HTML through <svelte:component />.

Another thing... is that I tried to use it in my App.svelte and it didn't work, even with the looping (until it opens), it claims that the method doesn't exist in "window".

Thank you so much for that! < 3

**Comment by icheer** [comment]
> But I think it could contain a component to be used through tags, even as a Web-Component used in HTML through <svelte:component />.
> 
> Another thing... is that I tried to use it in my App.svelte and it didn't work, even with the looping (until it opens), it claims that the method doesn't exist in "window".

You're welcome.

Yeah, because there is an IIFE function in my app.js, it exposes a object(webAssistant) into global window (and it makes sure that only exposes one time).

I think it's not a good practice because it makes every feature (such as .guideline, .intro, .toast, .cursor ...etc) injected into the global even if you don't need it. And makes it single instance (you cannot launch two toast or two cursor at the same time...)

It's my beginning attempt in web components with svelte (still not so familiar with svelte until now), maybe someday I'll completely rewrite the package in a better way when I collect enough skill with svelte : )

**Comment by icheer** [comment]
But there is still a good thing in some way: users don't need to write `import webAssistant from 'web-assistant'` or `import { guideline } from 'web-assitant`.
Instead, only need `import 'web-assistant'` and directly call `window.webAssistant.xxxx(JSON or JsonArray)` everywhere in their code.
(I think it's much easy to use and regardless of frontend framework or UI library, can be imported with npm or standalone script... for sure, it missed on-demand loading in this way...)
